### ISSUE TITLE
add instructions to readme

### ISSUE THREAD

**Issue by outflux3** [NicoKnoll/LightWire-Skin#2]
Per Mike Anthony's post: 

Install the skin into site/modules/InputfieldCKEditor/skins/lightwire
    In config.js, use the following:

```
CKEDITOR.editorConfig = function( config ) {
    config.skin = "lightwire,/site/modules/InputfieldCKEditor/skins/lightwire/";
};
```

By doing this, we need not put anything into wire/modules.

**Comment by nicoknoll** [comment]
Included it
